defaults:
  - /preprocessing/scaler@scaler: standard
  - /preprocessing/encoder@encoder: complex
  - _self_

_target_: sklearn.neighbors.KNeighborsRegressor

n_neighbors: 5

weights: uniform

algorithm: auto

leaf_size: 30

p: 2

metric: minkowski

n_jobs: ${training.n_jobs}

is_cat: ${preprocessing.encode_categorical}

is_scale: ${preprocessing.scale_numeric}

grid_params:
  model__n_neighbors: [3, 5, 7, 9, 11, 15, 21]
  model__weights: ['uniform', 'distance']
  model__metric: ['euclidean', 'manhattan', 'minkowski']
  model__p: [1, 2]
